import {
  FaCertificate,
  FaCheckCircle,
  FaWhatsapp,
  FaEnvelope,
  FaGraduationCap,
} from "react-icons/fa";

const Certificates = () => {
  return (
    <div className="min-h-screen bg-[#F5F7FA] p-6 md:p-10">

      {/* Header */}

      <div className="bg-gradient-to-r from-[#082B3A] via-[#0B4B63] to-[#126D89] rounded-3xl p-8 md:p-10 text-white shadow-xl">

        <div className="flex flex-col lg:flex-row items-center justify-between gap-8">

          <div>

            <div className="flex items-center gap-4">

              <div className="bg-yellow-400 text-[#082B3A] p-5 rounded-2xl">

                <FaCertificate className="text-5xl" />

              </div>

              <div>

                <h1 className="text-4xl md:text-5xl font-bold">
                  Course Certificate
                </h1>

                <p className="mt-3 text-gray-200 text-lg">
                  Celebrate your learning journey with an official certificate.
                </p>

              </div>

            </div>

          </div>

        </div>

      </div>

      {/* Main Card */}

      <div className="bg-white rounded-3xl shadow-xl mt-10 p-8 md:p-10">

        <div className="text-center">

          <div className="w-28 h-28 rounded-full bg-green-100 flex items-center justify-center mx-auto">

            <FaGraduationCap className="text-6xl text-green-600" />

          </div>

          <h2 className="text-3xl font-bold text-[#082B3A] mt-8">
            Certificate Status
          </h2>

          <p className="text-gray-600 mt-4 text-lg leading-8 max-w-3xl mx-auto">

            Once you successfully complete your enrolled course and meet all
            academy requirements, your official course completion certificate
            will be generated by the academy.

          </p>

        </div>

        {/* Features */}

        <div className="grid md:grid-cols-3 gap-6 mt-12">

          <div className="bg-green-50 rounded-2xl p-6 text-center border border-green-200">

            <FaCheckCircle className="text-5xl text-green-600 mx-auto mb-4" />

            <h3 className="text-xl font-bold text-[#082B3A]">
              Course Completed
            </h3>

            <p className="text-gray-600 mt-3">
              Successfully complete your course and fulfill all academy
              requirements.
            </p>

          </div>

          <div className="bg-blue-50 rounded-2xl p-6 text-center border border-blue-200">

            <FaEnvelope className="text-5xl text-blue-600 mx-auto mb-4" />

            <h3 className="text-xl font-bold text-[#082B3A]">
              Email Delivery
            </h3>

            <p className="text-gray-600 mt-3">
              Your certificate will be delivered to your registered email
              address in PDF format.
            </p>

          </div>

          <div className="bg-green-50 rounded-2xl p-6 text-center border border-green-200">

            <FaWhatsapp className="text-5xl text-green-600 mx-auto mb-4" />

            <h3 className="text-xl font-bold text-[#082B3A]">
              WhatsApp Delivery
            </h3>

            <p className="text-gray-600 mt-3">
              A copy of your certificate will also be shared on your registered
              WhatsApp number.
            </p>

          </div>

        </div>

        {/* Notice */}

        <div className="mt-12 bg-yellow-50 border-l-4 border-yellow-400 rounded-2xl p-6">

          <h3 className="text-2xl font-bold text-[#082B3A] mb-3">
            Important Information
          </h3>

          <ul className="space-y-3 text-gray-700 text-lg">

            <li>
              ✔ Certificates are issued only after successful course completion.
            </li>

            <li>
              ✔ All pending assignments, attendance, and evaluations must be
              completed.
            </li>

            <li>
              ✔ Certificates are digitally verified by the academy.
            </li>

            <li>
              ✔ Your certificate will automatically be sent to your registered
              Email and WhatsApp number.
            </li>

            <li>
              ✔ Please ensure your Email address and WhatsApp number are
              correct in your profile.
            </li>

          </ul>

        </div>

      </div>

    </div>
  );
};

export default Certificates;